# -*- coding: utf-8 -*-
"""test_pathfinder

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EGs-SyUplMAn1QwYL1Lx4SB8vlos5Aon
"""

import unittest
from my_pathfinder import Graph

class TestPathFinder(unittest.TestCase):
    def setUp(self):
        self.g = Graph()
        self.g.add_edge('A', 'B', 1)
        self.g.add_edge('B', 'C', 2)
        self.g.add_edge('A', 'C', 4)
        self.g.add_edge('C', 'D', 1)
        self.g.add_coordinates('A', 0, 0)
        self.g.add_coordinates('B', 1, 1)
        self.g.add_coordinates('C', 2, 1)
        self.g.add_coordinates('D', 3, 2)

    def test_dijkstra(self):
        path, dist = self.g.dijkstra('A', 'D')
        self.assertEqual(path, ['A', 'B', 'C', 'D'])
        self.assertEqual(dist, 4)

    def test_astar(self):
        path, dist = self.g.astar('A', 'D')
        self.assertEqual(path, ['A', 'B', 'C', 'D'])
        self.assertEqual(dist, 4)

unittest.main(argv=[''], exit=False)